### PR TITLE
Make app run under linux

### PR DESCRIPTION
**Pull request by sbrandtb**
... at least with the settings from `app/config.ini`.

On Windows, `os.path.normpath`, which is applied to all paths from the config.ini, normalizes forward slashes to backslashes. It does not do the other way around on Linux, so the way to go here should be to use forward slashes per default because it works on both.

I didn't change https://github.com/hanak/artshow-keeper/blob/master/app/test/data/config.ini though because it contains an absolute path and I don't know if this one is critical for you or if it can just be changed to a path relative to `$HOME` or the app directory. Tell me if I should change it.

### CODE REVIEW

**Comment by hanak** [comment]
If the suggested change to config.ini does not cause issue with Windows, let us use it. If there could be incompatibility issues, I would re-consider the idea. Is there some native python path replacement system which would allows to use something OS-independent? If so, let us use it.

**Comment by sbrandtb** [comment]
The code provided *is* OS independent. All paths from `config.ini` are filtered through this function: https://github.com/hanak/artshow-keeper/blob/master/app/config.py#L34-L37

```python
def __normalize_path(path):
    if not os.path.isabs(path):
       path = os.path.join(__appDir, path)
return os.path.normpath(path)
```

There, `os.path.normpath` does OS-independent normalization from forward to backward slashes - but not the other way around (see https://docs.python.org/3/library/os.path.html#os.path.normpath). That is why I had to change the backslashes to forward slashes.

Here a small script that shows this behaviour:

```python
import os.path

__appDir = os.path.dirname(__file__)

def __normalize_path(path):
    if not os.path.isabs(path):
       path = os.path.join(__appDir, path)
    return os.path.normpath(path)

print('app dir ->', __appDir)
print('./some/relative ->', __normalize_path('./some/local'))
print('/some/absolute ->', __normalize_path('/some/absolute'))
```

On Windows, Python 3.6:

```
app dir -> C:/Users/Sebastian/PycharmProjects/untitled
./some/relative -> C:\Users\Sebastian\PycharmProjects\untitled\some\relative
/some/absolute -> \some\absolute
```

As you can see, the forward slashes have been converted properly for the relative paths (so things in this merge request will just work). But for the absolute path, no drive letter has been prepended (how should it know?) and that's why I cannot change the `LOG_FILE` path in https://github.com/hanak/artshow-keeper/blob/master/app/test/data/config.ini because it contains a drive letter. I would suggest to not use absolute paths anyways - that would be the best approach.

But, TL;DR: This pull request is safe to merge.

**Comment by hanak** [comment]
Nice. Thank you.

**Comment by hanak** [comment]
Sorry for this. I have pressed wrong button.

**Pull request merged**
